### ISSUE TITLE
可不可以写个linux程序实现该功能？

### ISSUE THREAD

**Issue by qiurigao** [nobody3u/VGCTools#1]
目前linux平台没有第三方工具，网络上的配置大多是Vmess链接。
linux用户转换成json很麻烦。
包括像这种订阅链接https://v2ray.party/sub/v2ray.php

**Comment by nobody3u** [comment]
Linux的GUI太难写，主流图形库就有好多个互相打架
另一方面，我也不熟悉Linux所以不会以程序的方式来实现

订阅链接也许会以网页的方式提供编、解码功能
不过因为订阅包含服务器数量较多，暂时还没想好要怎么输入、输出数据

**Comment by qiurigao** [comment]
@nobody3u 我的意思是写个转换的命令行工具把链接转换成后写入json文件，然后v2ray直接调用就行了。
不是写GUI
gui的话有网页就够了。

**Comment by nobody3u** [comment]
也没这打算。
单纯解码编码，网页已经能完成，而且和系统无关随时随地都可以用。

如果加其他功能，这时候又会遇到和GUI一个的性质的问题。
比如在Archlinux用得好好的脚本，突然到了Debian或者更有个性的Openwrt用不了，
那时候我都不知道是再装个虚拟机好呢还是让他自己改源码好。

所以Linux的问题还是由Linux用户来解决比较好。

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
